services:
  db:
    image: postgres:16-alpine
    container_name: vending_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vending}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vending_pass}
      POSTGRES_DB: ${POSTGRES_DB:-vending}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vending" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vending_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vending_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - vending_network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vending_app_prod
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-vending}:${POSTGRES_PASSWORD:-vending_pass}@db:5432/${POSTGRES_DB:-vending}
      SECRET_KEY: ${SECRET_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      VENDISTA_API_BASE_URL: ${VENDISTA_API_BASE_URL:-https://api.vendista.ru}
      VENDISTA_API_TOKEN: ${VENDISTA_API_TOKEN}
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: "False"
      CORS_ORIGINS: ${CORS_ORIGINS:-https://t.me}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./backend/app:/app/app:ro
      - ./backend/pkgs:/pkgs
    networks:
      - vending_network
    command: >
      sh -c "
        pip install --no-index --find-links=/pkgs passlib bcrypt email-validator dnspython idna &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers
      "

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --protocol http2 run --token eyJhIjoiOTYwZmNkOTQ3YjkyYzI4Y2YyNzUyZWVjZWVmOTZmMDYiLCJ0IjoiMGZmYzI5OTEtMWU1NC00MmYxLTlmOTItNTIyYmNlNjE0OWUzIiwicyI6Ik56Y3lNR1V4TW1FdE56ZGhPQzAwT0dKakxUZzNaR1V0Wm1GaE5USmlNMkl4TTJJMyJ9
    networks:
      - vending_network
    depends_on:
      - frontend
      - app

volumes:
  postgres_data_prod:
    driver: local

networks:
  vending_network:
    driver: bridge
